"""email_proprietario não é mais fk de usuario

Revision ID: 00b5e1114fa5
Revises: 1a015348a1e3
Create Date: 2025-12-12 11:27:02.280435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b5e1114fa5'
down_revision: Union[str, Sequence[str], None] = '1a015348a1e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('evento_ibfk_3'), 'evento', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('evento_ibfk_3'), 'evento', 'usuario', ['email_proprietario'], ['email'])
    # ### end Alembic commands ###
