"""adição de horario inicio em evento e ocorrencia

Revision ID: 1a015348a1e3
Revises: 5d658d1f7723
Create Date: 2025-12-11 10:36:06.042359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a015348a1e3'
down_revision: Union[str, Sequence[str], None] = '5d658d1f7723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('horario_inicio', sa.Time(), nullable=True))
    op.add_column('ocorrencia_evento', sa.Column('horario_inicio', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ocorrencia_evento', 'horario_inicio')
    op.drop_column('evento', 'horario_inicio')
    # ### end Alembic commands ###
