"""rename notificacao.evento -> mensagem

Revision ID: 1fcc42f45756
Revises: 3b2602242bc4
Create Date: 2025-11-27 22:07:17.350633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fcc42f45756'
down_revision: Union[str, Sequence[str], None] = '3b2602242bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notificacao', sa.Column('mensagem', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notificacao', 'mensagem')
    # ### end Alembic commands ###
