"""initial from current models

Revision ID: 3b2602242bc4
Revises: 
Create Date: 2025-11-26 13:25:44.860910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2602242bc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('senha', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('senha', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_universidade', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('sigla', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_universidade'], ['universidade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('evento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_universidade', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_termino', sa.DateTime(), nullable=True),
    sa.Column('recorrencia', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.Column('id_proprietario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_proprietario'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_universidade'], ['universidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('evento', sa.String(length=255), nullable=True),
     sa.Column('mensagem', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_universidade', sa.Integer(), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('titulacao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_universidade'], ['universidade.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('aluno',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.Column('matricula', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('convidado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('status_vinculo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_evento'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disciplina',
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('id_professor', sa.Integer(), nullable=True),
    sa.Column('horario', sa.String(length=10), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_evento'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['id_professor'], ['professor.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_table('ocorrencia_evento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=True),
    sa.Column('local', sa.String(length=255), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_evento'], ['evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso_disciplina',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.Column('id_disciplina', sa.Integer(), nullable=True),
    sa.Column('creditos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id'], ),
    sa.ForeignKeyConstraint(['id_disciplina'], ['disciplina.id_evento'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disciplina_dias',
    sa.Column('id_disciplina', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['id_disciplina'], ['disciplina.id_evento'], ),
    sa.PrimaryKeyConstraint('id_disciplina', 'dia')
    )
    op.create_table('presenca',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_ocorrencia_evento', sa.Integer(), nullable=True),
    sa.Column('id_aluno', sa.Integer(), nullable=True),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_ocorrencia_evento'], ['ocorrencia_evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presenca')
    op.drop_table('disciplina_dias')
    op.drop_table('curso_disciplina')
    op.drop_table('ocorrencia_evento')
    op.drop_table('disciplina')
    op.drop_table('convidado')
    op.drop_table('aluno')
    op.drop_table('professor')
    op.drop_table('notificacao')
    op.drop_table('evento')
    op.drop_table('curso')
    op.drop_table('usuario')
    op.drop_table('universidade')
    # ### end Alembic commands ###
