"""adição de horario_termino em evento e ocorrencia

Revision ID: 5d658d1f7723
Revises: 6e9d696c4a58
Create Date: 2025-12-10 18:45:02.020064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d658d1f7723'
down_revision: Union[str, Sequence[str], None] = '6e9d696c4a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('horario_termino', sa.Time(), nullable=True))
    op.add_column('ocorrencia_evento', sa.Column('horario_termino', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ocorrencia_evento', 'horario_termino')
    op.drop_column('evento', 'horario_termino')
    # ### end Alembic commands ###
