"""remove titulacao and data_admissao from professor

Revision ID: 9d617f3c84ac
Revises: 1fcc42f45756
Create Date: 2025-11-28 16:55:03.573084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9d617f3c84ac'
down_revision: Union[str, Sequence[str], None] = '1fcc42f45756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professor', 'data_admissao')
    op.drop_column('professor', 'titulacao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professor', sa.Column('titulacao', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('professor', sa.Column('data_admissao', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
