"""descreva sua mudança aqui

Revision ID: 9f988fdfbd87
Revises: d1c5ea30b16a
Create Date: 2025-11-30 00:33:06.659176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9f988fdfbd87'
down_revision: Union[str, Sequence[str], None] = 'd1c5ea30b16a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curso', sa.Column('graduacao', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('evento_ibfk_1'), 'evento', type_='foreignkey')
    op.drop_column('evento', 'id_proprietario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('id_proprietario', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('evento_ibfk_1'), 'evento', 'usuario', ['id_proprietario'], ['id'])
    op.drop_column('curso', 'graduacao')
    # ### end Alembic commands ###
