"""mudei o nome da coluna recorrente para recorrencia e tambem mudei o tipo de boolean para string

Revision ID: d1c5ea30b16a
Revises: fa88b6b47481
Create Date: 2025-11-29 20:46:10.173554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd1c5ea30b16a'
down_revision: Union[str, Sequence[str], None] = 'fa88b6b47481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('recorrencia', sa.String(length=255), nullable=True))
    op.drop_column('evento', 'recorrente')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('recorrente', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('evento', 'recorrencia')
    # ### end Alembic commands ###
