"""adicionado nome em evento

Revision ID: d68dc225510c
Revises: 004254720b98
Create Date: 2025-12-06 14:12:37.895472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68dc225510c'
down_revision: Union[str, Sequence[str], None] = '004254720b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('nome', sa.String(length=255), nullable=True))
    op.add_column('evento', sa.Column('descricao', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evento', 'descricao')
    op.drop_column('evento', 'nome')
    # ### end Alembic commands ###
