"""Added all tables

Revision ID: dcdd896db864
Revises: 
Create Date: 2025-11-21 09:14:24.917195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcdd896db864'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Universidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuário',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Curso',
    sa.Column('idUniversidade', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('sigla', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['idUniversidade'], ['Universidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Evento',
    sa.Column('idUniversidade', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataInicio', sa.DateTime(), nullable=True),
    sa.Column('dataTermino', sa.DateTime(), nullable=True),
    sa.Column('recorrente', sa.Boolean(), nullable=True),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.Column('idproprietário', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idUniversidade'], ['Universidade.id'], ),
    sa.ForeignKeyConstraint(['idproprietário'], ['Usuário.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Notificação',
    sa.Column('idUsuário', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('evento', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['idUsuário'], ['Usuário.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Professor',
    sa.Column('idUsuário', sa.Integer(), nullable=False),
    sa.Column('idUniversidade', sa.Integer(), nullable=True),
    sa.Column('dataAdmissão', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['idUniversidade'], ['Universidade.id'], ),
    sa.ForeignKeyConstraint(['idUsuário'], ['Usuário.id'], ),
    sa.PrimaryKeyConstraint('idUsuário')
    )
    op.create_table('Aluno',
    sa.Column('idUsuário', sa.Integer(), nullable=False),
    sa.Column('idCurso', sa.Integer(), nullable=True),
    sa.Column('mátricula', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['idCurso'], ['Curso.id'], ),
    sa.ForeignKeyConstraint(['idUsuário'], ['Usuário.id'], ),
    sa.PrimaryKeyConstraint('idUsuário')
    )
    op.create_table('Convidado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idEvento', sa.Integer(), nullable=True),
    sa.Column('idUsuário', sa.Integer(), nullable=True),
    sa.Column('statusVinculo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['idEvento'], ['Evento.id'], ),
    sa.ForeignKeyConstraint(['idUsuário'], ['Usuário.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Disciplina',
    sa.Column('idEvento', sa.Integer(), nullable=False),
    sa.Column('idProfessor', sa.Integer(), nullable=True),
    sa.Column('horario', sa.String(length=10), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['idEvento'], ['Evento.id'], ),
    sa.ForeignKeyConstraint(['idProfessor'], ['Professor.idUsuário'], ),
    sa.PrimaryKeyConstraint('idEvento')
    )
    op.create_table('OcorrênciaEvento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idEvento', sa.Integer(), nullable=True),
    sa.Column('local', sa.String(length=255), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idEvento'], ['Evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CursoDisciplina',
    sa.Column('idCurso', sa.Integer(), nullable=True),
    sa.Column('idDisciplina', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idCurso'], ['Curso.id'], ),
    sa.ForeignKeyConstraint(['idDisciplina'], ['Disciplina.idEvento'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Presença',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idOcorrênciaEvento', sa.Integer(), nullable=True),
    sa.Column('idAluno', sa.Integer(), nullable=True),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['idAluno'], ['Aluno.idUsuário'], ),
    sa.ForeignKeyConstraint(['idOcorrênciaEvento'], ['OcorrênciaEvento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dDisciplina',
    sa.Column('idDisciplina', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['idDisciplina'], ['Disciplina.idEvento'], ),
    sa.PrimaryKeyConstraint('idDisciplina', 'dia')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dDisciplina')
    op.drop_table('Presença')
    op.drop_table('CursoDisciplina')
    op.drop_table('OcorrênciaEvento')
    op.drop_table('Disciplina')
    op.drop_table('Convidado')
    op.drop_table('Aluno')
    op.drop_table('Professor')
    op.drop_table('Notificação')
    op.drop_table('Evento')
    op.drop_table('Curso')
    op.drop_table('Usuário')
    op.drop_table('Universidade')
    # ### end Alembic commands ###
