"""coloquei as colunas nome e descrição no evento

Revision ID: ec4a6d263c56
Revises: df025cb4768f
Create Date: 2025-12-01 13:45:09.721424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec4a6d263c56'
down_revision: Union[str, Sequence[str], None] = 'df025cb4768f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
