"""mudei a relação usuario evento de id para email

Revision ID: fa88b6b47481
Revises: 9d617f3c84ac
Create Date: 2025-11-29 20:42:36.156160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fa88b6b47481'
down_revision: Union[str, Sequence[str], None] = '9d617f3c84ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The original autogenerated migration assumed the column
    # 'email_proprietario' already existed as INTEGER. In some DBs (dev
    # environments) the column may be absent or already present as a
    # String. Make the migration robust:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    cols = {c['name']: c for c in inspector.get_columns('evento')}

    # If email_proprietario does not exist, create it as VARCHAR(255).
    if 'email_proprietario' not in cols:
        op.add_column('evento', sa.Column('email_proprietario', sa.String(length=255), nullable=True))

        # If id_proprietario exists, try to migrate values -> usuario.email
        if 'id_proprietario' in cols:
            # Populate email_proprietario from usuario table joining on id_proprietario
            op.execute(
                """
                UPDATE evento e
                JOIN usuario u ON e.id_proprietario = u.id
                SET e.email_proprietario = u.email
                WHERE e.id_proprietario IS NOT NULL
                """
            )

    else:
        # If column exists but is INTEGER, alter it to VARCHAR
        col_type = cols['email_proprietario']['type']
        # MySQL INTEGER type appears as mysql.INTEGER in autogen; check by name
        if isinstance(col_type, mysql.INTEGER):
            op.alter_column('evento', 'email_proprietario',
                       existing_type=mysql.INTEGER(),
                       type_=sa.String(length=255),
                       existing_nullable=True)

    # Create/ensure foreign key on email_proprietario -> usuario.email
    # First, attempt to create the FK; if a constraint with the same
    # name exists elsewhere this will raise — alembic/autogenerate used None
    # to let the DB pick a name. Use try/except to avoid failing on second run.
    try:
        op.create_foreign_key(None, 'evento', 'usuario', ['email_proprietario'], ['email'])
    except Exception:
        # ignore if FK cannot be created (already exists)
        pass

    # If id_proprietario exists, drop it (we migrated values above)
    if 'id_proprietario' in cols:
        try:
            # Drop foreign key referencing id_proprietario if present; drop_column
            # will also remove constraints in most cases.
            op.drop_column('evento', 'id_proprietario')
        except Exception:
            # ignore if cannot drop (manual cleanup may be needed)
            pass

    # Other schema adjustments: handle existing columns safely
    notif_cols = {c['name']: c for c in inspector.get_columns('notificacao')}
    if 'mensagem' not in notif_cols:
        op.add_column('notificacao', sa.Column('mensagem', sa.String(length=255), nullable=True))

    prof_cols = {c['name']: c for c in inspector.get_columns('professor')}
    if 'titulacao' in prof_cols:
        try:
            op.drop_column('professor', 'titulacao')
        except Exception:
            pass
    if 'data_admissao' in prof_cols:
        try:
            op.drop_column('professor', 'data_admissao')
        except Exception:
            pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professor', sa.Column('data_admissao', sa.DATE(), nullable=True))
    op.add_column('professor', sa.Column('titulacao', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('notificacao', 'mensagem')
    op.add_column('evento', sa.Column('id_proprietario', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'evento', type_='foreignkey')
    op.alter_column('evento', 'email_proprietario',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
