"""mudei a relação usuario evento de id para email

Revision ID: fa88b6b47481
Revises: 9d617f3c84ac
Create Date: 2025-11-29 20:42:36.156160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fa88b6b47481'
down_revision: Union[str, Sequence[str], None] = '9d617f3c84ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evento', 'email_proprietario',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_foreign_key(None, 'evento', 'usuario', ['email_proprietario'], ['email'])
    op.drop_column('evento', 'id_proprietario')
    op.add_column('notificacao', sa.Column('mensagem', sa.String(length=255), nullable=True))
    op.drop_column('professor', 'titulacao')
    op.drop_column('professor', 'data_admissao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professor', sa.Column('data_admissao', sa.DATE(), nullable=True))
    op.add_column('professor', sa.Column('titulacao', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('notificacao', 'mensagem')
    op.add_column('evento', sa.Column('id_proprietario', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'evento', type_='foreignkey')
    op.alter_column('evento', 'email_proprietario',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
