"""create tables from models (ascii names)

Revision ID: b7c780098f52
Revises: 
Create Date: 2025-11-26 12:15:21.418076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c780098f52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Universidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('senha', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('senha', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Curso',
    sa.Column('idUniversidade', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('sigla', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['idUniversidade'], ['Universidade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Evento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idUniversidade', sa.Integer(), nullable=True),
    sa.Column('dataInicio', sa.DateTime(), nullable=True),
    sa.Column('dataTermino', sa.DateTime(), nullable=True),
    sa.Column('recorrente', sa.Boolean(), nullable=True),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.Column('idProprietario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idProprietario'], ['Usuario.id'], ),
    sa.ForeignKeyConstraint(['idUniversidade'], ['Universidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Notificacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('evento', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['idUsuario'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Professor',
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('idUniversidade', sa.Integer(), nullable=True),
    sa.Column('dataAdmissao', sa.Date(), nullable=True),
    sa.Column('titulacao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['idUniversidade'], ['Universidade.id'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('idUsuario')
    )
    op.create_table('Aluno',
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('idCurso', sa.Integer(), nullable=True),
    sa.Column('matricula', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['idCurso'], ['Curso.id'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('idUsuario')
    )
    op.create_table('Convidado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idEvento', sa.Integer(), nullable=True),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.Column('statusVinculo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['idEvento'], ['Evento.id'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Disciplina',
    sa.Column('idEvento', sa.Integer(), nullable=False),
    sa.Column('idProfessor', sa.Integer(), nullable=True),
    sa.Column('horario', sa.String(length=10), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['idEvento'], ['Evento.id'], ),
    sa.ForeignKeyConstraint(['idProfessor'], ['Professor.idUsuario'], ),
    sa.PrimaryKeyConstraint('idEvento')
    )
    op.create_table('OcorrenciaEvento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idEvento', sa.Integer(), nullable=True),
    sa.Column('local', sa.String(length=255), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idEvento'], ['Evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CursoDisciplina',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idCurso', sa.Integer(), nullable=True),
    sa.Column('idDisciplina', sa.Integer(), nullable=True),
    sa.Column('creditos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idCurso'], ['Curso.id'], ),
    sa.ForeignKeyConstraint(['idDisciplina'], ['Disciplina.idEvento'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Presenca',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idOcorrenciaEvento', sa.Integer(), nullable=True),
    sa.Column('idAluno', sa.Integer(), nullable=True),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['idAluno'], ['Aluno.idUsuario'], ),
    sa.ForeignKeyConstraint(['idOcorrenciaEvento'], ['OcorrenciaEvento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dDisciplina',
    sa.Column('idDisciplina', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['idDisciplina'], ['Disciplina.idEvento'], ),
    sa.PrimaryKeyConstraint('idDisciplina', 'dia')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dDisciplina')
    op.drop_table('Presenca')
    op.drop_table('CursoDisciplina')
    op.drop_table('OcorrenciaEvento')
    op.drop_table('Disciplina')
    op.drop_table('Convidado')
    op.drop_table('Aluno')
    op.drop_table('Professor')
    op.drop_table('Notificacao')
    op.drop_table('Evento')
    op.drop_table('Curso')
    op.drop_table('Usuario')
    op.drop_table('Universidade')
    # ### end Alembic commands ###
